version: '3.8'

services:
  phpcrm-db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  phpcrm-app:
    image: php:8.3-fpm-alpine
    volumes:
      - app_data:/var/www/html
    environment:
      - DATABASE_URL=pgsql://${DB_USER}:${DB_PASSWORD}@phpcrm-db:5432/${DB_NAME}
    command: >
      sh -c "apk add --no-cache postgresql-dev libpq-dev
      && docker-php-ext-install pdo pdo_pgsql
      && php-fpm"

  phpcrm-web:
    image: nginx:alpine
    volumes:
      - app_data:/var/www/html
      - type: tmpfs  # Solution clé pour Coolify
        target: /etc/nginx/conf.d/default.conf
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

volumes:
  postgres_data:
  app_data:

configs:
  nginx_config:
    file: ./nginx.conf
