version: '3.8'

services:
  phpcrm-db:
    image: 'postgres:16'
    restart: always
    volumes:
      - 'phpcrm-postgresql-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpcrm-app:
    image: 'php:8.3-fpm-alpine'
    restart: always
    volumes:
      - './phpcrm:/home/myownd/crm'
    environment:
      - 'DATABASE_URL=pgsql://${DB_USER}:${DB_PASSWORD}@phpcrm-db:5432/${DB_NAME}'
    working_dir: /home/myownd/crm
    depends_on:
      phpcrm-db:
        condition: service_healthy
    command: >
      sh -c "apk add --no-cache \
      postgresql-dev libpq-dev imap-dev libpng-dev libzip-dev && \
      docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
      docker-php-ext-configure imap && \
      docker-php-ext-install pdo pdo_pgsql pgsql mysqli imap gd zip && \
      apk del postgresql-dev libpq-dev && php-fpm && \
      chown -R nginx:nginx /home/myownd/crm && \
      chmod -R 777 /home/myownd/crm/uploads && \
      chmod -R 777 /home/myownd/crm/application/config && \
      chmod 777 /home/myownd/crm/application/config/config.php && \
      chmod 777 /home/myownd/crm/application/config/app-config-sample.php && \
      chmod -R 777 /home/myownd/crm/temp"

  phpcrm-web:
    image: 'nginx:alpine'
    restart: always
    volumes:
      - './phpcrm:/home/myownd/crm'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8443:8443'
    environment:
      - SERVICE_FQDN_CRM_8443
    depends_on:
      - phpcrm-app
    command: >
      sh -c "chown -R nginx:nginx /home/myownd/crm && \
      chmod -R 777 /home/myownd/crm/uploads && \
      chmod -R 777 /home/myownd/crm/application/config && \
      chmod 777 /home/myownd/crm/application/config/config.php && \
      chmod 777 /home/myownd/crm/application/config/app-config-sample.php && \
      chmod -R 777 /home/myownd/crm/temp && \
      exec nginx -g 'daemon off;'"

volumes:
  phpcrm-postgresql-data:
